### ISSUE TITLE
Build failed when I run "npm i" in either web or native

### ISSUE THREAD

**Issue by ghost** [TeamMaestro/angular-native-seed#102]
Hi,

I have just cloned angular-native-seed and run "npm i" in the root directory, then I get these errors (some of which I think might be ok):

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 

gypgyp  ERR!ERR!  build errorbuild error 
 
gypgyp  ERR!ERR!  stackstack Error: `make` failed with exit code: 2
 Error: `make` failed with exit code: 2
gypgyp  ERR! ERR!stack      at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
stackgyp     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
 gypERR!  stackERR!     at ChildProcess.emit (events.js:182:13)
 gypstack      at ChildProcess.emit (events.js:182:13)
ERR! gyp stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp gypERR!  ERR!System Darwin 17.6.0
 System Darwin 17.6.0
gyp gypERR!  commandERR!  "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
command "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR!gyp  cwdERR! /Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents
 gypcwd  /Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents
ERR!gyp  node -vERR! v10.4.0
 node -vgyp v10.4.0
 ERR!gyp  node-gyp -vERR! v3.6.2
 node-gyp -v v3.6.2
gyp gypERR!  ERR!not ok  
not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.4.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents
node-pre-gyp ERR! node -v v10.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/10.4.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/neigaard/work/angular/angular-native-seed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

4 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/neigaard/work/angular/angular-native-seed/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/Users/neigaard/work/angular/angular-native-seed/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/neigaard/work/angular/angular-native-seed/node_modules/node-sass
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1

> angular-native-seed@0.0.0 postinstall /Users/neigaard/work/angular/angular-native-seed
> node symlink.js

Configuring...
A symlink already exists.
npm WARN @angular-devkit/schematics@0.0.52 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.1.17 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by terryli0095** [comment]
Bump!
