### ISSUE TITLE
Webpack build issue with nativescript-angular/router/router.module.d.ts

### ISSUE THREAD

**Issue by dhananjaykumar880** [TeamMaestro/angular-native-seed#72]
Hi,

I am using angular-native-seed to build cross-platform mobile apps. and when I ran 'npm run phone-android-bundle', I am stuck with following error

![image](https://user-images.githubusercontent.com/4748110/32894228-7b215866-cadc-11e7-9804-1f4d231c4f6e.png)

Please help me

**Comment by sean-perkins** [comment]
Are all of your "native" angular modules marked with `NO_ERRORS_SCHEMA` on the `schemas` definition of their module?

**Comment by dhananjaykumar880** [comment]
yeah, I have added NO_ERRORS_SCHEMA in my native angular module.

**Comment by dhananjaykumar880** [comment]
Hey Sean,
please suggest. I am unable to resolve this as I am new in this technology.

**Comment by dhananjaykumar880** [comment]
Hey,
I don't understand to 'imports to reference the updated import schema'.
could you please elaborate it?

and I had imported 'ui/web-view' instead of 'tns-core-modules/ui/web-view'
should I have to import from 'tns-core-modules/ui/web-view' ?

**Comment by sean-perkins** [comment]
Yes, all the imports that come from a NS package, need to be imported from `tns-core-modules`.

**Comment by dhananjaykumar880** [comment]
But you did it like `ui/frame`

[see here](https://github.com/TeamMaestro/angular-native-seed/blob/master/nativescript/app/vendor-platform.android.ts)

**Comment by dhananjaykumar880** [comment]
I have changed it by `tns-core-modules/ui/frame` but still it is not working and throw below error
![image](https://user-images.githubusercontent.com/4748110/33168902-df7c1470-d042-11e7-89b0-4b82f11e9122.png)

**Comment by sean-perkins** [comment]
<img width="1680" alt="screen shot 2017-11-25 at 12 44 07 am" src="https://user-images.githubusercontent.com/13732623/33227805-cab9cb62-d179-11e7-9d80-ada17ba0f4bc.png">

I did a fresh clone of the repository, installed all dependencies, ran `npm run ios` from the `/nativescript` folder and then ran `npm run build-ios-bundle` with no problems.

Due to those items, I would assume your issue is external to the seed and related to your implementation.

**Comment by dhananjaykumar880** [comment]
Hey,

after your comment, I also tried to do from fresh code but it is not working with fresh too.
I had tried it in windows and mac both and I got same error on both

`Project successfully prepared (Android)
Executing after-prepare hook from /Users/alex/Documents/git/test/nativescript/hooks/after-prepare/nativescript-dev-android-snapshot.js
Executing after-prepare hook from /Users/alex/Documents/git/test/nativescript/hooks/after-prepare/nativescript-dev-sass.js
All SASS source files removed from app package
Building project...
Gradle build...

:config phase:  createDefaultIncludeFiles
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for /Users/alex/Documents/git/test/nativescript/platforms/android/configurations/tns-core-modules-widgets
Renaming plugin directory to flavor name: /Users/alex/Documents/git/test/nativescript/platforms/android/src/tns-core-modules-widgets -> /Users/alex/Documents/git/test/nativescript/platforms/android/src/F0

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in /Users/alex/Documents/git/test/nativescript/platforms/android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: /Users/alex/Documents/git/test/nativescript/platforms/android/configurations/include.gradle
        +applying configuration from: /Users/alex/Documents/git/test/nativescript/platforms/android/configurations/tns-core-modules-widgets/include.gradle

:config phase:  addAarDependencies
        +adding dependency: /Users/alex/Documents/git/test/nativescript/platforms/android/libs/aar/widgets-release.aar
Running full build
finished with reading lines with js files
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
/Users/alex/Documents/git/test/nativescript/platforms/android/src/main/java/com/tns/gen/java/lang/Object_frnal_ts_helpers_l58_c38__t.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alex/Documents/git/test/nativescript/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command ./gradlew failed with exit code 1
`
