### ISSUE TITLE
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.2.9".

### ISSUE THREAD

**Issue by collindutter** [TeamMaestro/angular-native-seed#87]
Upon a fresh clone and npm i, running ng build fails with:

`Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.2.9".
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.2.9".
    at Object.<anonymous> (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:27:11)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)`

**Comment by alexziskind1** [comment]
TypeScript version needs an update too (after the above error is fixed)

**Comment by sean-perkins** [comment]
Give master a fresh go now.

**Comment by collindutter** [comment]
Fixed!

**Comment by IvelinM** [comment]
Share - how did u fix it

**Comment by zhiyuancui** [comment]
I met the same issue today. how did you fix it?

**Comment by AlanKalep** [comment]
@collindutter what was the solution? i have the same error!
