### ISSUE TITLE
npm run build-ios-bundle fails

### ISSUE THREAD

**Issue by collindutter** [TeamMaestro/angular-native-seed#88]
On fresh clone, after running `npm i` in nativescript directory, `npm run build-ios-bundle` fails:

`Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/app/package.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at getPackageJson (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/nativescript-dev-webpack/projectHelpers.js:49:26)
    at GenerateBundleStarterPlugin.exports.GenerateBundleStarterPlugin.GenerateBundleStarterPlugin.generatePackageJson (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/nativescript-dev-webpack/plugins/GenerateBundleStarterPlugin.js:32:29)
    at Compiler.<anonymous> (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/nativescript-dev-webpack/plugins/GenerateBundleStarterPlugin.js:14:57)
    at next (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/tapable/lib/Tapable.js:204:14)
    at callback (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/copy-webpack-plugin/dist/index.js:71:17)
    at Object.finallyHandler (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/finally.js:39:23)
    at Object.tryCatcher (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Failed to find LaunchScreen.storyboard but it was specified in the Info.plist.
Consider updating the resources in app/App_Resources/iOS/.
A good starting point would be to create a new project and diff the changes with your current one.
Also the following repo may be helpful: https://github.com/NativeScript/template-hello-world/tree/master/App_Resources/iOS
We will now place an empty obsolete compatability white screen LauncScreen.xib for you in platforms/ios/nativescript/Resources/LaunchScreen.xib so your app may appear as it did in pre v2.1.0 versions of the ios runtime.
ENOENT: no such file or directory, scandir '/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/platforms/ios/nativescript/app'`

**Comment by collindutter** [comment]
Looks like it's an issue with `nativescript/fonts` directory being symlinked to /Users/sean/Documents/maestro/angular-native-seed/src/fonts. Updating it to the correct symlink for my system fixed it.
