### ISSUE TITLE
Could not resolve module ./app/+about/about.module

### ISSUE THREAD

**Issue by collindutter** [TeamMaestro/angular-native-seed#90]
On fresh clone, after running `npm i` in the `nativescript` directory, running `npm run build-ios-bundle` gets me this error:

`ERROR in Error: Could not resolve module ./app/+about/about.module relative to /Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/app/app/home/home.module.ts
    at StaticSymbolResolver.getSymbolByModule (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/packages/compiler/esm5/src/aot/static_symbol_resolver.js:760:7)
    at StaticReflector.resolveExternalReference (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/packages/compiler/esm5/src/aot/static_reflector.js:105:10)
    at parseLazyRoute (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/packages/compiler/esm5/src/aot/lazy_routes.js:81:2)
    at listLazyRoutes (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/packages/compiler/esm5/src/aot/lazy_routes.js:43:2)
    at visitLazyRoute (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/packages/compiler/esm5/src/aot/compiler.js:775:14)
    at AotCompiler.listLazyRoutes (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/packages/compiler/esm5/src/aot/compiler.js:743:17)
    at AngularCompilerProgram.listLazyRoutes (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/packages/compiler-cli/src/transformers/program.ts:196:26)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/packages/compiler-cli/src/ngtools_api.ts:95:34)
    at NativeScriptAngularCompilerPlugin._getLazyRoutesFromNgtools (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (/Users/collindutter/Documents/Programming/RideTrackr/angular-native-seed/nativescript/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:561:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3`

**Comment by sean-perkins** [comment]
Please look at the comment in the home.routes.tns.ts file:

https://github.com/TeamMaestro/angular-native-seed/blob/master/src/app/home/home.routes.tns.ts#L13
